DROP DATABASE IF EXISTS snet1;
CREATE DATABASE snet1 CHARACTER SET utf8mb4;
USE snet1;

CREATE TABLE `communities` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`),
  KEY `name` (`name`)
);

INSERT INTO `communities` (`id`, `name`) VALUES ('75', 'Automated 4thgeneration matrix');
INSERT INTO `communities` (`id`, `name`) VALUES ('5', 'Business-focused object-oriented implementation');
INSERT INTO `communities` (`id`, `name`) VALUES ('58', 'Centralized high-level hub');
INSERT INTO `communities` (`id`, `name`) VALUES ('41', 'Centralized radical complexity');
INSERT INTO `communities` (`id`, `name`) VALUES ('51', 'Cloned exuding time-frame');
INSERT INTO `communities` (`id`, `name`) VALUES ('12', 'Configurable object-oriented task-force');
INSERT INTO `communities` (`id`, `name`) VALUES ('63', 'Cross-group value-added alliance');
INSERT INTO `communities` (`id`, `name`) VALUES ('55', 'Cross-platform fault-tolerant framework');
INSERT INTO `communities` (`id`, `name`) VALUES ('24', 'Customer-focused systematic solution');
INSERT INTO `communities` (`id`, `name`) VALUES ('53', 'De-engineered exuding info-mediaries');
INSERT INTO `communities` (`id`, `name`) VALUES ('40', 'Decentralized zerotolerance analyzer');
INSERT INTO `communities` (`id`, `name`) VALUES ('42', 'Distributed multi-tasking circuit');
INSERT INTO `communities` (`id`, `name`) VALUES ('18', 'Distributed responsive extranet');
INSERT INTO `communities` (`id`, `name`) VALUES ('59', 'Diverse foreground hub');
INSERT INTO `communities` (`id`, `name`) VALUES ('60', 'Diverse radical ability');
INSERT INTO `communities` (`id`, `name`) VALUES ('22', 'Diverse systematic structure');
INSERT INTO `communities` (`id`, `name`) VALUES ('94', 'Down-sized mobile matrices');
INSERT INTO `communities` (`id`, `name`) VALUES ('100', 'Down-sized non-volatile focusgroup');
INSERT INTO `communities` (`id`, `name`) VALUES ('79', 'Enhanced 4thgeneration workforce');
INSERT INTO `communities` (`id`, `name`) VALUES ('84', 'Enterprise-wide 24hour instructionset');
INSERT INTO `communities` (`id`, `name`) VALUES ('86', 'Enterprise-wide client-server utilisation');
INSERT INTO `communities` (`id`, `name`) VALUES ('65', 'Enterprise-wide stable attitude');
INSERT INTO `communities` (`id`, `name`) VALUES ('26', 'Expanded logistical hierarchy');
INSERT INTO `communities` (`id`, `name`) VALUES ('89', 'Expanded responsive groupware');
INSERT INTO `communities` (`id`, `name`) VALUES ('31', 'Extended clear-thinking collaboration');
INSERT INTO `communities` (`id`, `name`) VALUES ('68', 'Extended dedicated access');
INSERT INTO `communities` (`id`, `name`) VALUES ('88', 'Extended local GraphicInterface');
INSERT INTO `communities` (`id`, `name`) VALUES ('52', 'Facetoface web-enabled moderator');
INSERT INTO `communities` (`id`, `name`) VALUES ('62', 'Front-line discrete product');
INSERT INTO `communities` (`id`, `name`) VALUES ('73', 'Front-line maximized localareanetwork');
INSERT INTO `communities` (`id`, `name`) VALUES ('44', 'Fully-configurable responsive moratorium');
INSERT INTO `communities` (`id`, `name`) VALUES ('30', 'Fully-configurable tangible implementation');
INSERT INTO `communities` (`id`, `name`) VALUES ('97', 'Function-based 5thgeneration model');
INSERT INTO `communities` (`id`, `name`) VALUES ('72', 'Function-based contextually-based challenge');
INSERT INTO `communities` (`id`, `name`) VALUES ('43', 'Fundamental interactive contingency');
INSERT INTO `communities` (`id`, `name`) VALUES ('71', 'Future-proofed intermediate framework');
INSERT INTO `communities` (`id`, `name`) VALUES ('4', 'Grass-roots background focusgroup');
INSERT INTO `communities` (`id`, `name`) VALUES ('21', 'Grass-roots neutral forecast');
INSERT INTO `communities` (`id`, `name`) VALUES ('35', 'Grass-roots optimizing strategy');
INSERT INTO `communities` (`id`, `name`) VALUES ('81', 'Grass-roots zeroadministration systemengine');
INSERT INTO `communities` (`id`, `name`) VALUES ('99', 'Innovative radical function');
INSERT INTO `communities` (`id`, `name`) VALUES ('34', 'Intuitive intangible analyzer');
INSERT INTO `communities` (`id`, `name`) VALUES ('46', 'Intuitive needs-based migration');
INSERT INTO `communities` (`id`, `name`) VALUES ('61', 'Inverse multimedia product');
INSERT INTO `communities` (`id`, `name`) VALUES ('25', 'Managed actuating groupware');
INSERT INTO `communities` (`id`, `name`) VALUES ('28', 'Mandatory motivating customerloyalty');
INSERT INTO `communities` (`id`, `name`) VALUES ('56', 'Multi-channelled 24/7 protocol');
INSERT INTO `communities` (`id`, `name`) VALUES ('29', 'Multi-channelled methodical firmware');
INSERT INTO `communities` (`id`, `name`) VALUES ('64', 'Multi-lateral explicit policy');
INSERT INTO `communities` (`id`, `name`) VALUES ('67', 'Multi-layered bifurcated solution');
INSERT INTO `communities` (`id`, `name`) VALUES ('14', 'Multi-layered explicit systemengine');
INSERT INTO `communities` (`id`, `name`) VALUES ('32', 'Multi-layered value-added installation');
INSERT INTO `communities` (`id`, `name`) VALUES ('23', 'Networked multimedia artificialintelligence');
INSERT INTO `communities` (`id`, `name`) VALUES ('19', 'Open-architected executive project');
INSERT INTO `communities` (`id`, `name`) VALUES ('33', 'Open-architected mission-critical GraphicalUserInterface');
INSERT INTO `communities` (`id`, `name`) VALUES ('98', 'Operative bifurcated array');
INSERT INTO `communities` (`id`, `name`) VALUES ('45', 'Operative zeroadministration orchestration');
INSERT INTO `communities` (`id`, `name`) VALUES ('87', 'Optional content-based firmware');
INSERT INTO `communities` (`id`, `name`) VALUES ('93', 'Persevering 3rdgeneration forecast');
INSERT INTO `communities` (`id`, `name`) VALUES ('10', 'Persistent regional product');
INSERT INTO `communities` (`id`, `name`) VALUES ('20', 'Phased value-added time-frame');
INSERT INTO `communities` (`id`, `name`) VALUES ('8', 'Polarised encompassing firmware');
INSERT INTO `communities` (`id`, `name`) VALUES ('70', 'Polarised grid-enabled interface');
INSERT INTO `communities` (`id`, `name`) VALUES ('78', 'Polarised mission-critical conglomeration');
INSERT INTO `communities` (`id`, `name`) VALUES ('77', 'Pre-emptive contextually-based flexibility');
INSERT INTO `communities` (`id`, `name`) VALUES ('27', 'Pre-emptive hybrid utilisation');
INSERT INTO `communities` (`id`, `name`) VALUES ('3', 'Profit-focused background throughput');
INSERT INTO `communities` (`id`, `name`) VALUES ('80', 'Programmable bandwidth-monitored access');
INSERT INTO `communities` (`id`, `name`) VALUES ('83', 'Programmable zerotolerance extranet');
INSERT INTO `communities` (`id`, `name`) VALUES ('54', 'Public-key grid-enabled customerloyalty');
INSERT INTO `communities` (`id`, `name`) VALUES ('49', 'Public-key grid-enabled structure');
INSERT INTO `communities` (`id`, `name`) VALUES ('15', 'Public-key radical interface');
INSERT INTO `communities` (`id`, `name`) VALUES ('1', 'Quality-focused non-volatile core');
INSERT INTO `communities` (`id`, `name`) VALUES ('2', 'Re-contextualized eco-centric extranet');
INSERT INTO `communities` (`id`, `name`) VALUES ('76', 'Re-contextualized systemic benchmark');
INSERT INTO `communities` (`id`, `name`) VALUES ('11', 'Re-contextualized uniform capability');
INSERT INTO `communities` (`id`, `name`) VALUES ('47', 'Re-engineered solution-oriented projection');
INSERT INTO `communities` (`id`, `name`) VALUES ('82', 'Reactive 5thgeneration standardization');
INSERT INTO `communities` (`id`, `name`) VALUES ('39', 'Reactive leadingedge flexibility');
INSERT INTO `communities` (`id`, `name`) VALUES ('6', 'Reactive multi-state function');
INSERT INTO `communities` (`id`, `name`) VALUES ('66', 'Reverse-engineered solution-oriented functionalities');
INSERT INTO `communities` (`id`, `name`) VALUES ('16', 'Right-sized 5thgeneration definition');
INSERT INTO `communities` (`id`, `name`) VALUES ('38', 'Right-sized clear-thinking hub');
INSERT INTO `communities` (`id`, `name`) VALUES ('96', 'Robust global approach');
INSERT INTO `communities` (`id`, `name`) VALUES ('95', 'Secured cohesive GraphicInterface');
INSERT INTO `communities` (`id`, `name`) VALUES ('48', 'Secured encompassing support');
INSERT INTO `communities` (`id`, `name`) VALUES ('69', 'Secured high-level systemengine');
INSERT INTO `communities` (`id`, `name`) VALUES ('90', 'Streamlined well-modulated customerloyalty');
INSERT INTO `communities` (`id`, `name`) VALUES ('85', 'Synergistic background model');
INSERT INTO `communities` (`id`, `name`) VALUES ('57', 'Synergistic didactic time-frame');
INSERT INTO `communities` (`id`, `name`) VALUES ('13', 'Synergized explicit workforce');
INSERT INTO `communities` (`id`, `name`) VALUES ('50', 'Synergized fresh-thinking methodology');
INSERT INTO `communities` (`id`, `name`) VALUES ('92', 'Synergized heuristic customerloyalty');
INSERT INTO `communities` (`id`, `name`) VALUES ('9', 'Up-sized bi-directional encryption');
INSERT INTO `communities` (`id`, `name`) VALUES ('37', 'Up-sized impactful analyzer');
INSERT INTO `communities` (`id`, `name`) VALUES ('36', 'Up-sized intermediate algorithm');
INSERT INTO `communities` (`id`, `name`) VALUES ('17', 'User-centric demand-driven task-force');
INSERT INTO `communities` (`id`, `name`) VALUES ('74', 'Virtual executive matrix');
INSERT INTO `communities` (`id`, `name`) VALUES ('91', 'Vision-oriented optimal customerloyalty');
INSERT INTO `communities` (`id`, `name`) VALUES ('7', 'Visionary intermediate focusgroup');